[PROTOCOLS]
Virtual Screening = [
    {"tag": "section", "text": "Docking", "icon": "bookmark.png", "children": [
        {"tag": "protocol", "value": "ProtGninaDocking", "text": "default"},
        {"tag": "protocol", "value": "ProtGninaCovalentDocking", "text": "default"},
        {"tag": "protocol", "value": "ProtGninaScore", "text": "default"}
    ]}
    ]
